trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - obj/*
      - bin/*
      - "*.md"

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - obj/*
      - bin/*
      - "*.md"

resources:
  repositories:
    - repository: common-pipelines
      type: github
      name: "jeevanthespark/common-pipelines"
      ref: main
      endpoint: "jeevanthespark"

extends:
  template: /templates/pipelines/common-app-ci.yaml@common-pipelines
  parameters:
    appBuildConfig:
      serviceName: "devproject"
      appProjectPath: "./src/Api/Api.csproj"
      appFrameworkType: "dotnet"
      frameworkVersion: "8.x"
      buildConfiguration: "Release"
      testProjectPath: "./test/ApiTests/ApiTests.csproj"
